package com.example.civicpulse;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

@Data
@Entity // Tells JPA that this class is a blueprint for a database table.
public class CivicIssue {

    @Id // Marks this field as the primary key for the table.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the ID to be auto-generated by the database.
    private Long id;

    private String category;
    private String description;
    private double latitude;
    private double longitude;
    private String status = "New"; // Sets a default value for new issues.

    @CreationTimestamp // Automatically sets this field to the current time when an issue is created.
    private Instant createdAt;
}