# render.yaml - Final Version
# Defines the services for the CivicPulse application.

databases:
  # This section tells Render to create a database with this name.
  - name: civicpulse-db-prod
    plan: free

services:
  # This section defines our Spring Boot backend service.
  - type: web
    name: civicpulse-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      # This is the ONLY environment variable we need for the database.
      # Spring Boot automatically parses the user, password, host, and database name
      # from this single connection string.
      - key: DATABASE_URL
        fromDatabase:
          name: civicpulse-db-prod
          property: connectionString